---
# file: server.yml

- hosts: servers
  remote_user: pi
  vars_files:
    - vars/ssh_keys.yml
    - vars/config.yml
  roles:
    - {role: init}
    - {role: common, tags: ['common']}

- hosts: kubernetes_master
  remote_user: root
  vars_files:
    - vars/ssh_keys.yml
    - vars/config.yml
  roles:
    - {role: kubernetes-master}

- hosts: kubernetes_workers
  remote_user: root
  vars_files:
    - vars/ssh_keys.yml
    - vars/config.yml
  roles:
    - {role: kubernetes-worker}
