---
# file: roles/kubernetes/tasks/packages.yml

- name: Install base packages
  apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes
  tags:
    - packages

- name: Install top packages
  apt:
    name: "{{ top_packages }}"
    state: present
    update_cache: yes
  tags:
    - packages

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update all packages to the latest version
  apt:
    upgrade: dist
